name: GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at 00:00 UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: gargi-cpu
          outputs: |
            dist/github-contribution-snake.svg
            dist/github-contribution-snake-dark.svg?palette=github-dark

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
